apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: release-tracker-frontend
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: helm/frontend
    repoURL: https://github.com/mayank-kr-s/k8s-release-tracker.git
    targetRevision: main
    helm:
      valueFiles: []
  sources: []
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      enabled: true
