server:
  port: 8080

spring:
  application:
    name: deployment-tracker-service
  datasource:
    url: jdbc:h2:mem:trackerdb
    driverClassName: org.h2.Driver
    username: sa
    password: password
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# Expose metrics for Kubernetes & Prometheus
management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,metrics
  endpoint:
    health:
      show-details: always
  metrics:
    tags:
      application: ${spring.application.name}